version: '3.5'

services:
    db:
        restart: always
        image: postgres:16-alpine
        container_name: db
        env_file:
            - path: ./.env
              required: true
        ports:
            - '${POSTGRES_PORT}:5432'
